### ISSUE TITLE
upgrade solid to 0.24.0?

### ISSUE THREAD

**Issue by 0x241F31** [mikeplus64/solid-typefu-router5#6]
I'm trying to compile but getting some errors. Could I ask you to update solid version? New version uses `mergeProps` instead of `assignProps` keyword, and seems like this is one breaking change.
https://github.com/ryansolid/solid/releases/tag/v0.24.0

**Comment by mikeplus64** [comment]
I upgraded the solid-js version that's used here and now get a build error coming from `babel-plugin-jsx-dom-expressions` which I believe `babel-preset-solid` uses. 
```
rollup v2.23.0
bundles src/index.tsx → dist/index.js, dist/index.es.js...
[!] (plugin babel) TypeError: /home/mike/Code/solid-typefu-router5/src/components/Link.tsx: Cannot read property 'events' of undefined
src/components/Link.tsx
TypeError: /home/mike/Code/solid-typefu-router5/src/components/Link.tsx: Cannot read property 'events' of undefined
    at /home/mike/Code/solid-typefu-router5/node_modules/babel-plugin-jsx-dom-expressions/index.js:767:44
    at Array.forEach (<anonymous>)
    at transformAttributes (/home/mike/Code/solid-typefu-router5/node_modules/babel-plugin-jsx-dom-expressions/index.js:645:6)
    at transformElement (/home/mike/Code/solid-typefu-router5/node_modules/babel-plugin-jsx-dom-expressions/index.js:476:3)
    at transformNode (/home/mike/Code/solid-typefu-router5/node_modules/babel-plugin-jsx-dom-expressions/index.js:1910:12)
    at PluginPass.transformJSX (/home/mike/Code/solid-typefu-router5/node_modules/babel-plugin-jsx-dom-expressions/index.js:1871:18)
    at Object.newFn (/home/mike/Code/solid-typefu-router5/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/home/mike/Code/solid-typefu-router5/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/mike/Code/solid-typefu-router5/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/mike/Code/solid-typefu-router5/node_modules/@babel/traverse/lib/path/context.js:92:31)
```

**Comment by mikeplus64** [comment]
I fixed the issue last weekish and forgot to close this issue. I don't have huge confidence in it because I don't have a test suite beyond clicking through the example (suggestions welcome), but that and my project I use this in do seem to work.
